create table "public"."users_projects" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "group_id" bigint,
    "joined_at" timestamp with time zone not null default now(),
    "is_active" boolean not null
);


alter table "public"."users_projects" enable row level security;

alter table "public"."projects" add column "skill_list" text[];

alter table "public"."projects" disable row level security;

CREATE UNIQUE INDEX users_projects_pkey ON public.users_projects USING btree (id);

alter table "public"."users_projects" add constraint "users_projects_pkey" PRIMARY KEY using index "users_projects_pkey";

alter table "public"."users_projects" add constraint "users_projects_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) not valid;

alter table "public"."users_projects" validate constraint "users_projects_group_id_fkey";

alter table "public"."users_projects" add constraint "users_projects_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."users_projects" validate constraint "users_projects_user_id_fkey";

grant delete on table "public"."users_projects" to "anon";

grant insert on table "public"."users_projects" to "anon";

grant references on table "public"."users_projects" to "anon";

grant select on table "public"."users_projects" to "anon";

grant trigger on table "public"."users_projects" to "anon";

grant truncate on table "public"."users_projects" to "anon";

grant update on table "public"."users_projects" to "anon";

grant delete on table "public"."users_projects" to "authenticated";

grant insert on table "public"."users_projects" to "authenticated";

grant references on table "public"."users_projects" to "authenticated";

grant select on table "public"."users_projects" to "authenticated";

grant trigger on table "public"."users_projects" to "authenticated";

grant truncate on table "public"."users_projects" to "authenticated";

grant update on table "public"."users_projects" to "authenticated";

grant delete on table "public"."users_projects" to "service_role";

grant insert on table "public"."users_projects" to "service_role";

grant references on table "public"."users_projects" to "service_role";

grant select on table "public"."users_projects" to "service_role";

grant trigger on table "public"."users_projects" to "service_role";

grant truncate on table "public"."users_projects" to "service_role";

grant update on table "public"."users_projects" to "service_role";


